### ISSUE TITLE
API error destroys state

### ISSUE THREAD

**Issue by seblau** [shoutem/redux-io#44]
Hi, I am using `shoutem/redux-io` to update data via a `PATCH` request. The updated data contains an email address which is validated on the server side. If the email address is not valid, the API returns an HTTP 400 error code. At this point on the client side the `UPDATE_ERROR` action is fired, and the state does not contain any data anymore:

![screen shot 2017-10-16 at 19 41 36](https://user-images.githubusercontent.com/3884582/31626467-1222f0e4-b2aa-11e7-88af-ec9d9018c5bd.png)

Is this an expected behaviour of `shoutem/redux-io`?

**Comment by vedrani** [comment]
Hi,

Can you specify redux-io version, and reducers you are using?
Based on screen shoot you are sending, I guess it's a `resource` reducer.

Expected behaviour for `resource` would be to keep older data with invalid + idle status, waiting for `find` action to be dispatched to fetch new data from server.

**Comment by seblau** [comment]
It's `@shoutem/redux-io@1.3.1`. For your information the problem occurs in the [`shoutem.auth`](https://github.com/shoutem/extensions/tree/master/shoutem-auth) extension and the reducers looks like: 

```
const userReducer = combineReducers({
  user: chainReducers([
    resource(USER_PROFILE_SCHEMA),
    resource(USER_PROFILE_IMAGE_SCHEMA),
  ]),
  session_id: (state = '') => state,
  access_token: (state = '') => state,
  success: (state = '') => state,
  token: (state = '') => state,
  data: (state = '') => state
});

export default preventStateRehydration(
  combineReducers({
    appsettings: resource(APP_SETTINGS_SCHEMA),
    auth: chainReducers([
      sessionReducer,
      resource(USER_SCHEMA),
      resource(USER_CREDENTIALS_SCHEMA),
      resource(USER_CUSTOMER_CREDENTIALS_SCHEMA),
      resource(USER_FACEBOOK_CREDENTIALS_SCHEMA),
      userReducer,
    ]),
  })
);
```

**Comment by vedrani** [comment]
Hi,
Every dispatched action `(find, update, create, remove` has `*_ERROR` action dispatched as side-effect of error occurred during fetch.
Resource reducer should on `UPDATE_ERROR` become idle, invalid with unchanged state. Redux-io only flags state with error on `LOAD_ERROR`.
To access error on `UPDATE_ERROR` you need to define `errorHandler` in `reject` or `catch` function on `dispatch` of update action.

```
dispatch(update(...)).catch(errorHandler);
```

```
dispatch(update(...)).then(..., errorHandler);
```

Where `errorHandler` is defined as:

```
function errorHandler(action) {
	const { payload, error } = action;
	// extract error from payload like .status, 
}
```

We are working on documenting redux-io, I hope we will have it soon.

You can see a test that checks your use case
https://github.com/shoutem/redux-io/blob/release/v1/test/reducers/resource.spec.js#L323

Regarding `shoutem.auth` extension I suggest you open issue on Shoutem Extensions [repo](https://github.com/shoutem/extensions/issues). And I already told my team that `shoutem.auth` has a potential bug.
