### ISSUE TITLE
Wouldn't it be a memory leak?

### ISSUE THREAD

**Issue by kgdev** [shoutem/redux-io#49]
https://github.com/shoutem/redux-io/blob/14e84d2f214191a98a5d8c486a02f1f4e853a198/src/denormalizer/getCollection.js#L9

**Comment by kgdev** [comment]
memoize does not clear the history.

**Comment by kgdev** [comment]
Also, by default _.memoize only caches the first argument.

**Comment by vedrani** [comment]
Thanks for the info, you are absolutely right. I will fix it as soon as possible. What version of redux-io are you using?

**Comment by vedrani** [comment]
Solved with 3.1.0-beta.10
